const fs = require('fs');
const path = require('path');

const AUDHD_PATH = path.join(__dirname, '../_analysis/audhd/app.js');
const OUTPUT_PATH = path.join(__dirname, '../seed_full_content.sql');

function extractDaysArray(filePath) {
    console.log(`Reading file: ${filePath}`);
    const content = fs.readFileSync(filePath, 'utf8');

    // Find the start of the days array
    const daysStartIndex = content.indexOf('days: [');
    if (daysStartIndex === -1) {
        console.error('Could not find days array');
        return null;
    }

    // Find the end of the days array by counting brackets
    let bracketCount = 0;
    let inArray = false;
    let endIndex = daysStartIndex;

    for (let i = daysStartIndex; i < content.length; i++) {
        const char = content[i];

        if (char === '[') {
            bracketCount++;
            inArray = true;
        } else if (char === ']') {
            bracketCount--;
            if (inArray && bracketCount === 0) {
                endIndex = i + 1;
                break;
            }
        }
    }

    // Extract the days array content
    const daysArrayString = content.substring(daysStartIndex + 6, endIndex); // +6 to skip "days: "

    // Convert to valid JSON by wrapping in object
    const jsonString = `{"days": ${daysArrayString}}`;

    try {
        const data = JSON.parse(jsonString);
        return data.days;
    } catch (e) {
        console.error('Error parsing days array:', e.message);
        // Try using eval as fallback
        try {
            const days = eval(`(${daysArrayString})`);
            return days;
        } catch (e2) {
            console.error('Eval also failed:', e2.message);
            return null;
        }
    }
}

function generateSQL() {
    console.log('Extracting AUDHD course data...');
    const days = extractDaysArray(AUDHD_PATH);

    if (!days) {
        console.error('Failed to extract days array');
        return;
    }

    console.log(`Extracted ${days.length} days of content`);

    let sql = `-- Full Content Migration Seed
-- Generated by scripts/generate_seed_v3.js
-- Contains ${days.length} days of lesson content

-- 1. Add content_data column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'challenge_tasks' AND column_name = 'content_data') THEN
        ALTER TABLE challenge_tasks ADD COLUMN content_data JSONB;
    END IF;
END $$;

`;

    // Generate updates for AUDHD challenge
    sql += `\n-- Updating content for audhd-relationship-30-day\n`;
    sql += `DO $$
DECLARE
    v_challenge_id INTEGER;
BEGIN
    SELECT id INTO v_challenge_id FROM challenges WHERE slug = 'audhd-relationship-30-day';
    
    IF v_challenge_id IS NULL THEN
        RAISE EXCEPTION 'Challenge not found: audhd-relationship-30-day';
    END IF;
`;

    let processedCount = 0;
    days.forEach(day => {
        if (!day.modules || day.modules.length === 0) {
            console.log(`Skipping day ${day.day} - no modules`);
            return;
        }

        try {
            const contentData = {
                modules: day.modules,
                dailyChallenge: day.dailyChallenge || null
            };

            const jsonContent = JSON.stringify(contentData).replace(/'/g, "''");  // Escape single quotes for SQL

            sql += `
    -- Day ${day.day}: ${day.title || 'Untitled'}
    UPDATE challenge_tasks 
    SET content_data = '${jsonContent}'::jsonb
    WHERE challenge_id = v_challenge_id AND day_number = ${day.day};
`;
            processedCount++;
        } catch (e) {
            console.error(`Error processing day ${day.day}:`, e.message);
        }
    });

    sql += `
    RAISE NOTICE 'Updated content_data for % days', ${processedCount};
END $$;
`;

    fs.writeFileSync(OUTPUT_PATH, sql);
    console.log(`\nGenerated SQL at ${OUTPUT_PATH}`);
    console.log(`Total days processed: ${processedCount} out of ${days.length}`);
}

generateSQL();
