const fs = require('fs');
const path = require('path');

const AUDHD_PATH = path.join(__dirname, '../_analysis/audhd/app.js');
const CODEPENDENCY_PATH = path.join(__dirname, '../_analysis/codependency/app.js');
const OUTPUT_PATH = path.join(__dirname, '../seed_full_content.sql');

function extractData(filePath) {
    const content = fs.readFileSync(filePath, 'utf8');

    // Mock browser globals to prevent ReferenceError when requiring browser-based files
    global.window = {};
    global.document = {
        getElementById: () => ({ textContent: '', addEventListener: () => { } }),
        querySelector: () => ({ textContent: '', addEventListener: () => { } }),
        querySelectorAll: () => []
    };

    // Replace "const courseData =" with "module.exports ="
    const newContent = content.replace('const courseData =', 'module.exports =');

    const tempPath = path.join(__dirname, `temp_${path.basename(filePath)}`);
    fs.writeFileSync(tempPath, newContent);

    try {
        const data = require(tempPath);
        // Clean up
        delete require.cache[require.resolve(tempPath)];
        fs.unlinkSync(tempPath);

        // Clean up globals
        delete global.window;
        delete global.document;

        return data;
    } catch (e) {
        console.error(`Error parsing ${filePath}:`, e);
        if (fs.existsSync(tempPath)) fs.unlinkSync(tempPath);

        // Clean up globals even on error
        delete global.window;
        delete global.document;

        return null;
    }
}

function generateSQL() {
    console.log('Extracting AUDHD data...');
    const audhdData = extractData(AUDHD_PATH);
    console.log('AUDHD data extracted:', audhdData ? `${audhdData.days?.length || 0} days` : 'null');

    console.log('Extracting Codependency data...');
    const codependencyData = extractData(CODEPENDENCY_PATH);
    console.log('Codependency data extracted:', codependencyData ? `${codependencyData.days?.length || 0} days` : 'null');

    let sql = `-- Full Content Migration Seed
-- Generated by scripts/generate_seed.js

-- 1. Add content_data column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'challenge_tasks' AND column_name = 'content_data') THEN
        ALTER TABLE challenge_tasks ADD COLUMN content_data JSONB;
    END IF;
END $$;

`;

    // Helper to generate updates
    const generateUpdates = (slug, data) => {
        if (!data || !data.days) return;

        sql += `\n-- Updating content for ${slug}\n`;
        sql += `DO $$
DECLARE
    v_challenge_id INTEGER;
BEGIN
    SELECT id INTO v_challenge_id FROM challenges WHERE slug = '${slug}';
`;

        data.days.forEach(day => {
            if (!day.modules) return;

            // Escape single quotes in JSON
            // We need to be careful with JSON.stringify. Postgres string literals use '' to escape '.
            // So we replace ' with ''.
            // Also, we need to handle backslashes if any.

            const jsonContent = JSON.stringify({
                modules: day.modules,
                dailyChallenge: day.dailyChallenge
            }).replace(/'/g, "''");

            sql += `
    UPDATE challenge_tasks 
    SET content_data = '${jsonContent}'::jsonb
    WHERE challenge_id = v_challenge_id AND day_number = ${day.day};
`;
        });

        sql += `END $$;\n`;
    };

    if (audhdData) generateUpdates('audhd-relationship-30-day', audhdData);
    if (codependencyData) generateUpdates('codependency-7-day', codependencyData);

    fs.writeFileSync(OUTPUT_PATH, sql);
    console.log(`Generated SQL at ${OUTPUT_PATH}`);
}

generateSQL();
