const fs = require('fs');
const path = require('path');

const AUDHD_PATH = path.join(__dirname, '../_analysis/audhd/app.js');
const OUTPUT_PATH = path.join(__dirname, '../seed_full_content.sql');

function extractCourseData(filePath) {
    console.log(`Reading file: ${filePath}`);
    const content = fs.readFileSync(filePath, 'utf8');

    // Find the courseData object
    const courseDataMatch = content.match(/const courseData\s*=\s*(\{[\s\S]*?\n\};)/);

    if (!courseDataMatch) {
        console.error('Could not find courseData in file');
        return null;
    }

    // Extract just the object part
    const dataString = courseDataMatch[1];

    // Use eval in a controlled way to parse the JavaScript object
    // This is safe because we control the source file
    try {
        const courseData = eval(`(${dataString})`);
        return courseData;
    } catch (e) {
        console.error('Error parsing courseData:', e.message);
        return null;
    }
}

function generateSQL() {
    console.log('Extracting AUDHD course data...');
    const audhdData = extractCourseData(AUDHD_PATH);

    if (!audhdData) {
        console.error('Failed to extract AUDHD data');
        return;
    }

    console.log(`Extracted ${audhdData.days?.length || 0} days of content`);

    let sql = `-- Full Content Migration Seed
-- Generated by scripts/generate_seed_v2.js

-- 1. Add content_data column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'challenge_tasks' AND column_name = 'content_data') THEN
        ALTER TABLE challenge_tasks ADD COLUMN content_data JSONB;
    END IF;
END $$;

`;

    // Generate updates for AUDHD challenge
    sql += `\n-- Updating content for audhd-relationship-30-day\n`;
    sql += `DO $$
DECLARE
    v_challenge_id INTEGER;
BEGIN
    SELECT id INTO v_challenge_id FROM challenges WHERE slug = 'audhd-relationship-30-day';
`;

    audhdData.days.forEach(day => {
        if (!day.modules || day.modules.length === 0) {
            console.log(`Skipping day ${day.day} - no modules`);
            return;
        }

        const jsonContent = JSON.stringify({
            modules: day.modules,
            dailyChallenge: day.dailyChallenge
        }).replace(/'/g, "''");  // Escape single quotes for SQL

        sql += `
    UPDATE challenge_tasks 
    SET content_data = '${jsonContent}'::jsonb
    WHERE challenge_id = v_challenge_id AND day_number = ${day.day};
`;
    });

    sql += `END $$;\n`;

    fs.writeFileSync(OUTPUT_PATH, sql);
    console.log(`\nGenerated SQL at ${OUTPUT_PATH}`);
    console.log(`Total days processed: ${audhdData.days.length}`);
}

generateSQL();
